@startuml
'arrows meaning:
"1"  -right-> "2" : "one to one"
"2"  -right-{ "3" : "one to many"
@enduml

@startuml
'conceptional model
skinparam class {
  BackgroundColor White
  BorderColor Black
}
class user
class cardboard
class square

user  -right-{ cardboard
cardboard  -right-{ square

@enduml

@startuml
'logical data mode

' --- Entities ---
entity "user" as user {
' unique generated primary key
  userId: Char
  --
  name: Char
}
entity "cardboard" as cardboard {
' unique generated primary key
  id: Char
  --
  name: Char
' foreign key from user
' delete if user was deleted from db
  userId: String
}
entity "square" as square {
' composite primary key:
  cardboardId + squareId
  --
  ' square num inside 1 cardboard is limited by screen size
  id: Int
  ' foreign key from cardboard
  ' delete if cardboard was deleted from db
  cardboardId
  startX: Int
  startY: Int
  endX: Int
  endY: Int
}

' --- relationships ---
user -down-{ cardboard : \
 "user can create/delete/edit \n\
cardboard"

cardboard -down-{ square : \
"user can manipulate squares \n\
of opened cardboard"

@enduml
