app {
  name = "grille-encoder"
  version = "1.0.0"
  environment = "dev"
}

server {
  host = "localhost"
  port = 8080
}

database {
  source {
    url = "jdbc:sqlite:cardboardPool2.db"
    driver = "org.sqlite.JDBC"
    user = ""
    password = "" // TODO pass the password from local machine to here or smthng
  }
  maxConnections = 10
  connectionTimeout = 30000
}

myDatabaseConfig {
  poolName = "AuthMeSQLitePool"
  dataSourceClassName = "org.sqlite.SQLiteDataSource"
  jdbcUrl = "jdbc:sqlite:plugins/AuthMe/cardboardPool2.db"
  maxLifetime = 60000
  idleTimeout = 45000
  maximumPoolSize = 50
  url = "jdbc:sqlite:cardboardPool1.db"
  connectionTimeout = 30000
}

# TODO Should be the DB for ZIO config
# https://github.com/zio/zio-protoquill?tab=readme-ov-file
