app {
  name = "grilleEncoder"
  version = "1.0.0"
  environment = "dev"
}

server {
  host = "localhost"
  port = 8080
}

database {
  source {
    url = "jdbc:sqlite:cardboardPool2.db"
    driver = "org.sqlite.JDBC"
    user = ""
    password = "" // TODO pass the password from local machine to here or smthng
  }
  maxConnections = 10
  connectionTimeout = 30000
}

myDatabaseConfig {
  dataSourceClassName = "org.sqlite.SQLiteDataSource"
  dataSource.url = "jdbc:sqlite:cardboardPoll.db"
}

# TODO Should be the DB for ZIO config
# https://github.com/zio/zio-protoquill?tab=readme-ov-file
